# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
comics = Comic.create([
{title: 'The Amazing Spider-Man', issue: '233', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '234', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '235', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '236', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '237', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '238', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '239', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '240', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '241', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '242', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '243', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '244', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '245', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '246', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '247', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '248', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '249', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '250', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '251', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '252', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '253', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '254', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '255', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '256', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '257', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '258', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '259', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '260', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '261', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '262', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '263', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '264', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '265', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '266', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '267', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '268', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '269', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '270', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '271', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '272', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '273', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '274', publisher: 'Marvel'},
{title: 'The Amazing Spider-Man', issue: '275', publisher: 'Marvel'},
{title: 'The Avengers', issue: '333', publisher: 'Marvel'},
{title: 'The Avengers', issue: '334', publisher: 'Marvel'},
{title: 'The Avengers', issue: '335', publisher: 'Marvel'},
{title: 'The Avengers', issue: '336', publisher: 'Marvel'},
{title: 'The Avengers', issue: '337', publisher: 'Marvel'},
{title: 'The Avengers', issue: '338', publisher: 'Marvel'},
{title: 'The Avengers', issue: '339', publisher: 'Marvel'},
{title: 'The Avengers', issue: '340', publisher: 'Marvel'},
{title: 'The Avengers', issue: '341', publisher: 'Marvel'},
{title: 'The Avengers', issue: '342', publisher: 'Marvel'},
{title: 'The Avengers', issue: '343', publisher: 'Marvel'},
{title: 'The Avengers', issue: '344', publisher: 'Marvel'},
{title: 'The Avengers', issue: '345', publisher: 'Marvel'},
{title: 'The Avengers', issue: '346', publisher: 'Marvel'},
{title: 'The Avengers', issue: '347', publisher: 'Marvel'},
{title: 'The Avengers', issue: '348', publisher: 'Marvel'},
{title: 'The Avengers', issue: '349', publisher: 'Marvel'},
{title: 'The Avengers', issue: '350', publisher: 'Marvel'},
{title: 'The Avengers', issue: '351', publisher: 'Marvel'},
{title: 'The Avengers', issue: '352', publisher: 'Marvel'},
{title: 'The Avengers', issue: '353', publisher: 'Marvel'},
{title: 'The Avengers', issue: '354', publisher: 'Marvel'},
{title: 'The Avengers', issue: '355', publisher: 'Marvel'},
{title: 'The Avengers', issue: '356', publisher: 'Marvel'},
{title: 'The Avengers', issue: '357', publisher: 'Marvel'},
{title: 'The Avengers', issue: '358', publisher: 'Marvel'},
{title: 'The Avengers', issue: '359', publisher: 'Marvel'},
{title: 'The Avengers', issue: '360', publisher: 'Marvel'},
{title: 'The Avengers', issue: '361', publisher: 'Marvel'},
{title: 'The Avengers', issue: '362', publisher: 'Marvel'},
{title: 'Batman', issue: '455', publisher: 'DC Comics'},
{title: 'Batman', issue: '456', publisher: 'DC Comics'},
{title: 'Batman', issue: '457', publisher: 'DC Comics'},
{title: 'Batman', issue: '458', publisher: 'DC Comics'},
{title: 'Batman', issue: '459', publisher: 'DC Comics'},
{title: 'Batman', issue: '460', publisher: 'DC Comics'},
{title: 'Batman', issue: '461', publisher: 'DC Comics'},
{title: 'Batman', issue: '462', publisher: 'DC Comics'},
{title: 'Batman', issue: '463', publisher: 'DC Comics'},
{title: 'Batman', issue: '464', publisher: 'DC Comics'},
{title: 'Batman', issue: '465', publisher: 'DC Comics'},
{title: 'Batman', issue: '466', publisher: 'DC Comics'},
{title: 'Batman', issue: '467', publisher: 'DC Comics'},
{title: 'Batman', issue: '468', publisher: 'DC Comics'},
{title: 'Batman', issue: '469', publisher: 'DC Comics'},
{title: 'Batman', issue: '470', publisher: 'DC Comics'},
{title: 'Batman', issue: '471', publisher: 'DC Comics'},
{title: 'Batman', issue: '472', publisher: 'DC Comics'},
{title: 'Batman', issue: '473', publisher: 'DC Comics'},
{title: 'Batman', issue: '474', publisher: 'DC Comics'},
{title: 'Batman', issue: '475', publisher: 'DC Comics'},
{title: 'Batman', issue: '476', publisher: 'DC Comics'},
{title: 'Batman', issue: '477', publisher: 'DC Comics'},
{title: 'Batman', issue: '478', publisher: 'DC Comics'},
{title: 'Batman', issue: '479', publisher: 'DC Comics'},
{title: 'Batman', issue: '480', publisher: 'DC Comics'},
{title: 'Batman', issue: '481', publisher: 'DC Comics'},
{title: 'Batman', issue: '482', publisher: 'DC Comics'},
{title: 'Batman', issue: '483', publisher: 'DC Comics'},
{title: 'Batman', issue: '484', publisher: 'DC Comics'},
{title: 'Batman', issue: '485', publisher: 'DC Comics'},
{title: 'Batman', issue: '486', publisher: 'DC Comics'},
{title: 'Batman', issue: '487', publisher: 'DC Comics'},
{title: 'Batman', issue: '488', publisher: 'DC Comics'},
{title: 'Fantastic Four', issue: '288', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '289', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '290', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '291', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '292', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '293', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '294', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '295', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '296', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '297', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '298', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '299', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '300', publisher: 'Marvel'},
{title: 'Fantastic Four', issue: '301', publisher: 'Marvel'},
{title: 'Superman', issue: '305', publisher: 'DC Comics'},
{title: 'Superman', issue: '306', publisher: 'DC Comics'},
{title: 'Superman', issue: '307', publisher: 'DC Comics'},
{title: 'Superman', issue: '308', publisher: 'DC Comics'},
{title: 'Superman', issue: '309', publisher: 'DC Comics'},
{title: 'Superman', issue: '310', publisher: 'DC Comics'},
{title: 'Superman', issue: '311', publisher: 'DC Comics'},
{title: 'Superman', issue: '312', publisher: 'DC Comics'},
{title: 'Superman', issue: '313', publisher: 'DC Comics'},
{title: 'Superman', issue: '314', publisher: 'DC Comics'},
{title: 'Superman', issue: '315', publisher: 'DC Comics'},
{title: 'Superman', issue: '316', publisher: 'DC Comics'},
{title: 'Superman', issue: '317', publisher: 'DC Comics'},
{title: 'Superman', issue: '318', publisher: 'DC Comics'},
{title: 'Superman', issue: '319', publisher: 'DC Comics'},
{title: 'Superman', issue: '320', publisher: 'DC Comics'},
{title: 'Superman', issue: '321', publisher: 'DC Comics'},
{title: 'Superman', issue: '322', publisher: 'DC Comics'},
{title: 'Superman', issue: '323', publisher: 'DC Comics'},
{title: 'Superman', issue: '324', publisher: 'DC Comics'},
{title: 'Superman', issue: '325', publisher: 'DC Comics'}])
